name: life_assistant
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  provider: ^6.1.1

  # Ses efektleri (GÜNCEL)
  audioplayers: ^6.0.0
  lottie: ^1.2.2

  # language sayfası için dosya seçimi  
  file_picker: ^8.1.4  # Dosya seçme penceresi açmak için
  csv: ^6.0.0          # Seçilen CSV dosyasını anlamlı veriye çevirmek için

  # Adım Sayar ve Sensörler
  pedometer: ^4.0.0        # Telefonun adım sensörüne erişim
  permission_handler: ^11.3.0 # İzinleri (Activity Recognition) istemek için

  # UUID
  uuid: ^4.2.2
  intl: ^0.18.0
  fl_chart: ^0.66.0        # Çubuk grafikler (Bar Chart) için

  # Routing
  go_router: ^13.2.0

  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.2

  # Hive Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Hive Codegen
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/animations/  # Lottie dosyaları için
    # Veya tüm assets klasörünü ekleyin:
    # - assets/